"Тз15"
m00rl00n/java-shareit pull request #4
Opened 2023-08-03 14:43 UTC by m00rl00n

2023-08-03 19:01 UTC, EugeneLenkevich requested changes
Привет, Виктория, спасибо за PR

В целом все отлично, все на своем месте, отметил только лишь пару совсем небольших моментиков :)

2023-08-03 19:01 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingDtoMapper.java
> +        bookingDtoReturned.setStart(LocalDateTime.parse(booking.getStart()
А тут точно стоит парсить даты, при перекладывании из сущности в дто, вроде ж везде типа одны и те же или это так сделано копирование объектов?  :)

2023-08-03 19:01 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size, sort);
Вот эта строчка попадается несколько раз, может ее в метод :)

2023-08-03 19:01 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
findAll()

Выгребать все данные из табьлички довольно опасно, там может быть очень много данных, а точно нужны все записи, может можно какие то учлосия добавить, вытащить только то что релевантно текущему пользователю в данном месте, например? :)

2023-08-04 13:25 UTC, m00rl00n commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingDtoMapper.java
> +        bookingDtoReturned.setStart(LocalDateTime.parse(booking.getStart()
Да, это остатки мои экспериментов, все работало и я не стала трогать)) Удалила

2023-08-04 13:25 UTC, m00rl00n commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size, sort);
Сделала метод, спасибо :)

2023-08-04 13:29 UTC, m00rl00n commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
Эта правка очень сильно важна? Вообщем, я вот полностью с ней согласна и вроде понимаю как сделать. Через репозиторий из таблицы вытаскивать относительно юзера, но я часов 5 пыталась исправить и у меня принципиально 6 тестов падают в постмане. Может есть какая-то подсказка, допускаю, что глаза замылислись и не вижу чего-то простого.

2023-08-04 13:34 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingDtoMapper.java
> +        bookingDtoReturned.setStart(LocalDateTime.parse(booking.getStart()
Мутный код лучше удалять, чтоыб потом голову не ломать :)

2023-08-04 13:35 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
Я вот про тесты особо не подскажу, потому пусть остается как есть, в учебном проекте не принципально,но в реальной жизни это была бы потенциальная проблема)

2023-08-04 13:36 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-08-04 16:17 UTC, m00rl00n commented on src/main/java/ru/practicum/shareit/request/service/RequestServiceImpl.java
> +        List<Item> items = itemRepository.findAll();
Спасибо большое за ревью :)

2023-08-10 13:23 UTC, merged